baseURL = "http://tweeds.io/"
languageCode = "en-us"
title = "TWEEDS | The workshop in environmental economics and data science"
theme = "timer-hugo"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
googleAnalytics = "UA-88887510-3"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/v2/

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name = "About"
url = "/about"
weight = 2
[[menu.nav]]
name = "FAQ"
url = "/faq"
weight = 3
[[menu.nav]]
name = "Logistics"
url = "/logistics"
weight = 4
[[menu.nav]]
name = "Program"
url = "/program"
weight = 5
# [[menu.nav]]
# name = "Contact"
# url = "/contact"
# weight = 5

# Site Params
[params]
home = "Home"
dateFormat = "6 January 2006"
#
# You can use either an image or text as logo.
# To use an image use 'logo' (logo itself) and 'logo_alt' (alternative text if image cannot displayed)
# To use text as logo use 'logo_text'
# logo = "images/logos/tweeds_tight_smaller.png"
logo_text = "TWEEDS"
logo_alt = "TWEEDS"

# Banner Section
[params.banner]
enable = true
bgImage = "images/slider.jpg"
heading = "The workshop in environmental <br> economics and data science"
description = "Join us in Portland, Oregon on March 27 and 28 (2020) for the second iteration of TWEEDS—an intimate workshop focused on the methodological frontiers of environmental economics and data science."
# btn = false
btn = true
# btnText = "Apply to attend!"
# btnURL = "https://edrubin.typeform.com/to/ZM16BZ"
btnText = "Mailing list"
btnURL = "https://edrubin.typeform.com/to/GXk3q2"
[[params.banner.flipText]]
title = "air quality"
[[params.banner.flipText]]
title = "machine learning"
[[params.banner.flipText]]
title = "inequality"
[[params.banner.flipText]]
title = "remote sensing"
[[params.banner.flipText]]
title = "visualization"
[[params.banner.flipText]]
title = "reproducibility"
[[params.banner.flipText]]
title = "health"
[[params.banner.flipText]]
title = "spatial data analysis"
[[params.banner.flipText]]
title = "truth"

# Homepage About Section
[params.about]
enable = true
title = "when + where"
content = "27–28 March 2020 <br> <br> The University of Oregon's White Stag Building <br> Portland, Oregon <br> <br> Registration costs (upon acceptance)<br>  $75 for students<br>  $150 for everyone else <br> <br> Applications were <b>due 05 January 2020</b>. <br> <br> Please contact <a href=\"mailto:ed@tweeds.io?Subject=TWEEDS\" class=\"email\" target=\"_blank\">Ed Rubin</a> with any additional questions."
image = "images/portland/portland_white_stag.jpg"

# Call to Action
[params.cta]
enable = true
title = "Interested?"
content = "Join our mailing list"
btn = true
btnText = "Mailing list"
btnURL = "https://edrubin.typeform.com/to/GXk3q2"

# Portfolio Section On Homepage
[params.portfolio]
enable = true
title = "speakers"
subtitle= "Keynote speaker and presenters currently on the agenda."

# Feature Product Section
[params.featureProduct]
enable = false
title = "SOME OF OUR FEATURES WORKS"
subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

# Footer section
[params.footer]
customized = true # Set this variable to true if you customized the design.
copyright_owner = "Themefisher"
copyright_since = "2018"
# [[params.footer.social]]
# icon = "ion-social-facebook"
# link = "https://facebook.com"
[[params.footer.social]]
icon = "ion-social-twitter"
link = "https://twitter.com/tweedsio"
# [[params.footer.social]]
# icon = "ion-social-instagram"
# link = "https://instagram.com"
# [[params.footer.social]]
# icon = "ion-social-linkedin"
# link = "https://linkedin.com"
# [[params.footer.social]]
# icon = "ion-social-googleplus"
# link = "https://googleplus.com"
[[params.footer.social]]
icon = "ion-social-github"
link = "https://github.com/edrubin/tweeds"
[[params.footer.social]]
icon = "ion-paper-airplane"
link = "mailto:ed@tweeds.io?Subject=TWEEDS"
